---
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker GPG key to apt
  apt_key:
    file: /tmp/docker.gpg
    state: present

- name: Clean up Docker GPG key file
  file:
    path: /tmp/docker.gpg
    state: absent

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} test"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
# docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

- name: Install Docker
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
